### PR TITLE
Allow multiple link buttons on one message

### PR DESCRIPTION
**Pull request by NickIsADev**
yes, this was tested

*even if this isn't the best solution, I brought the bug to your attention 🙂*

### CODE REVIEW

**Comment by Bilal2453** [comment]
It is best to provide the code to reproduce whatever you are talking about for more context so we are both on the same page. I assume you mean that Link Buttons cannot be duplicated even though Discord allows for it?

**Comment by NickIsADev** [comment]
Discordia-components restricts you from adding two link buttons to a message because both of those link buttons' ID's are `nil`, since none of the link buttons were provided an ID. On the same line of the file change in this commit, discordia-components checks if there are 2 components with the same ID. Since it finds two Link Buttons with an ID of `nil`, it matches the two and thinks that there are two buttons with the same ID. The edited part of code makes discordia-components check if the component contains a `url`, AKA if the component is a link button.
> To reproduce this, simply try sending a message with two Link Buttons attached to it.

**Comment by Bilal2453** [comment]
I haven't really tested this one, but I do remember something along those lines.  I can't remember how link buttons are handled exactly, so for now I will just merge this.

**Comment by Bilal2453** [comment]
Also seems like you requested this to be merged into dev instead of main, no worries will handle that

**Comment by NickIsADev** [comment]
Yup, `main` doesnt have ComponentsContainer so I just used dev

**Pull request merged**
